version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/app/data/database.sqlite
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  sqlite_data:
  redis_data: 